Electrons hazelhen
markusbattarbee/vlasiator-public pull request #5
Opened 2020-06-15 09:28 UTC by alhom

Static ionosphere implementation for TEMPO electrons, as a new sysboundary type.

2020-06-15 11:57 UTC, markusbattarbee commented on sysboundary/staticionosphere.cpp
> +         Readparameters::add(pop + "_staticionosphere.fluffiness", "Inertia of boundary smoothing when copying neighbour's moments and velocity distributions (0=completely constant boundaries, 1=neig
Since it's static, fluffiness is not relevant.

2020-06-17 09:50 UTC, markusbattarbee requested changes
Just the fluffiness thing out

2020-06-22 09:47 UTC, markusbattarbee commented
Tested to work with the getnormalvector out? I think that was indeed purged from fieldsolver stuff some while back, just checking

2020-06-22 10:24 UTC, alhom commented
It does not appear anywhere else than ionosphere class, so it shouldn't matter. Let me verify that, though, I'm not sure if I ran that with actual ionosphere in the domain.

2020-06-22 14:39 UTC, alhom commented
Works without the getnormalfield function.

2020-06-22 15:18 UTC, merged